export const ACTION_IMPORT_KEY = 'ACTION_IMPORT_KEY';
export const ACTION_BALANCE_ETH = 'ACTION_BALANCE_ETH';
export const ACTION_BALANCE_TOKENS = 'ACTION_BALANCE_TOKENS';
export const ACTION_BUY_TOKENS = 'ACTION_BUY_TOKENS';