export const BOT_MESSAGE_RECEIVED = 'BOT_MESSAGE_RECEIVED';
export const BOT_MESSAGE_SENT = 'BOT_MESSAGE_SENT';
export const BOT_MESSAGE_ERROR = 'BOT_MESSAGE_ERROR';
export const USER_MESSAGE_RECEIVED = 'USER_MESSAGE_RECEIVED';
export const USER_MESSAGE_SAVED = 'USER_MESSAGE_SAVED';
export const USER_MESSAGE_ERROR = 'USER_MESSAGE_ERROR';

